/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors:{
        html: '#f06529',
        css: '#2961f1',
        js: '#f7df1e',
        angular: '#dd1b16',
        scss: '#cd6779',
        ts: '#007acc',
        figma: '#a259ff',
        github: '#24292e',
        react: '#61dbfb',
        tailwind:'#06b6d4',
        backgroundColor: '#fff',   
        btnColor: '#0987f2',
        btnTextColor: '#fff',
        projectCardBg: '#ffffff00',
        textColor: '#222',
        formTextColor: '#555',
        tooterTextColor: '#888',
        backgroundColorDark: '#222',
        btnColorDark: '#fff',
        btnTextColorDark:'#222',
        projectCardBgDark: '#fff',
        textColorDark: '#fff',
        formTextColorDark: '#fff',
        footerTextColorDark: '#bbb',
      }
    },
  },
  safelist: [
    'bg-html',
    'bg-css',
    'bg-js',
    'bg-angular',
    'bg-scss',
    'bg-ts',
    'bg-figma',
    'bg-github',
    'bg-react',
    'bg-tailwind',
    'bg-pink-500',
    'border-html',
    'border-css',
    'border-js',
    'border-angular',
    'border-scss',
    'border-ts',
    'border-figma',
    'border-github',
    'border-react',
    'border-tailwind',
    'border-pink-500',
    'text-html',
    'text-css',
    'text-js',
    'text-angular',
    'text-scss',
    'text-ts',
    'text-figma',
    'text-github',
    'text-react',
    'text-tailwind',
    'text-pink-500'
  ],
  plugins: [],
}

